Repository protofire/omen-exchange, pull requests merged in 2020-10, with the labels that each got.

#1149 Create Market Redesign #1122
  app/src/components/button/button_container/index.tsx
  app/src/components/common/form/date_field/index.tsx
  app/src/components/common/form/dropdown/index.tsx
  app/src/components/common/form/form_row/index.tsx
  app/src/components/common/form/form_state_button/index.tsx
  app/src/components/common/form/question_input/index.tsx
  app/src/components/common/form/simiple_textfield/index.tsx
  app/src/components/common/index.ts
  app/src/components/common/layout/header/index.tsx
  app/src/components/market/common/additional_market_data/index.tsx
  app/src/components/market/common/arbitrator_icon/index.tsx
  app/src/components/market/common/arbitrators/index.tsx
  app/src/components/market/common/categories/index.tsx
  app/src/components/market/common/common_styled/index.tsx
  app/src/components/market/common/display_arbitrator/index.tsx
  app/src/components/market/common/history_chart/chart.tsx
  app/src/components/market/common/market_resolution_message/index.tsx
  app/src/components/market/common/set_allowance/index.tsx
  app/src/components/market/common/transaction_details_card/index.tsx
  app/src/components/market/common/transaction_details_line/index.tsx
  app/src/components/market/common/warning_message/index.tsx
  app/src/components/market/sections/market_create/market_wizard_creator.tsx
  app/src/components/market/sections/market_create/steps/items/ask_question_step.tsx
  app/src/components/market/sections/market_create/steps/items/funding_and_fee_step.tsx
  app/src/components/market/sections/market_create/steps/outcomes/index.spec.tsx
  app/src/components/market/sections/market_create/steps/outcomes/index.tsx
  app/src/components/market/sections/market_profile/market_status/open.tsx
  app/src/global.d.ts
  app/src/theme/index.js
  app/src/theme/overrides/datepicker_styles_override.tsx
  app/src/util/networks.ts
  app/src/util/tools.ts
Labels: Omen Version 2, UI

#1188 added metamask check if user is connected for reality link
  app/src/components/market/common/additional_market_data/index.tsx
  app/src/components/market/common/display_resolution/index.tsx
  app/src/components/market/sections/market_profile/market_status/open.tsx
  app/src/hooks/useRealityLink.tsx
Labels: bug

#1213 Fix search input
  app/src/components/market/sections/market_list/market_home_container.tsx
Labels: UI, bug

#1212 Update probability placeholder
  app/src/components/market/sections/market_create/steps/outcomes/index.tsx
Labels: UI
