Repository protofire/omen-exchange, pull requests merged in 2020-11, with the labels that each got.

#1253 Scalar market creation back-end
  app/src/common/constants.ts
  app/src/components/market/sections/market_create/market_wizard_creator_container.tsx
  app/src/components/market/sections/market_create/steps/items/ask_question_step.tsx
  app/src/components/market/sections/market_profile/market_status/closed_scalar.tsx
  app/src/components/market/sections/market_profile/market_status/open_scalar.tsx
  app/src/components/market/sections/market_profile/market_view.tsx
  app/src/hooks/useContracts.tsx
  app/src/services/conditional_token.ts
  app/src/services/cpk.ts
  app/src/services/realitio.ts
  app/src/util/networks.ts
  app/src/util/tools.spec.ts
  app/src/util/tools.ts
Labels: Scalar Market

#1301 deleted breakpoint for three dot wrapping
  app/src/components/common/form/more_menu/index.tsx
  app/src/components/common/text/subsection_title_wrapper/index.tsx
  app/src/components/market/common/market_top_details_closed/index.tsx
  app/src/components/market/common/market_top_details_open/index.tsx
  app/src/hooks/useWindowDimensions.tsx
Labels: Mobile, UI, bug

#1334 changed text when user has no markets
  app/src/components/market/sections/market_list/market_home.tsx
Labels: UI

#1332 changed so default curation source any is not shown
  app/src/components/market/sections/market_list/market_home_container.tsx
Labels: optimization

#1331 fixed mobile cramping for pool table
  app/src/components/market/sections/market_pooling/market_pool_liquidity.tsx
Labels: Mobile

#1330 My Markets Ending soon is showing the soonest ending markets at the end of the list #1271
  app/src/components/market/sections/market_list/market_home.tsx
  app/src/components/market/sections/market_list/market_home_container.tsx
Labels: UI

#1319 added back button, changed position of warning and added button wrapp…
  app/src/components/market/common/grid_transaction_details/index.tsx
  app/src/components/market/sections/market_navigation/index.tsx
  app/src/components/market/sections/market_pooling/market_pool_liquidity.tsx
  app/src/theme/index.js
Labels: UI

#1348 back button now goes to main page
  app/src/components/market/sections/market_verify/market_verify.tsx
Labels: verification

#1355 Fix/#1341
  app/src/components/common/icons/IconTick.tsx
  app/src/components/common/icons/index.ts
  app/src/components/market/sections/market_verify/img/tick.svg
  app/src/components/market/sections/market_verify/option/dxdao_curation.tsx
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1359 style changes to the challenge section
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1366 added one more condition for border top
  app/src/components/market/sections/market_profile/market_status/open.tsx
Labels: UI

#1370 added hyperlink for the verified on the kleros curation
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1367 changed size of icon and border only shown when not active
  app/src/components/market/sections/market_verify/market_verify.tsx
Labels: verification

#1364 added verified remove section
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1368 changed margin of description to 20px
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1350 verify shown only for open markets
  app/src/components/market/sections/market_navigation/index.tsx
  app/src/components/market/sections/market_profile/market_status/closed.tsx
  app/src/components/market/sections/market_profile/market_status/open.tsx
Labels: verification

#1357 changed location of exported styled components
  app/src/components/market/common/common_styled/index.tsx
  app/src/components/market/sections/market_verify/market_verify.tsx
  app/src/components/market/sections/market_verify/option/dxdao_curation.tsx
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1381 updated button so that they have outline styling instaed of secondary
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1379 changed so that ETH is bolded for not verified market
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1374 changed styles of verification process icons
  app/src/components/common/icons/IconSchedule.tsx
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1386 Feature/#1371
  app/src/components/market/sections/market_verify/market_verify.tsx
  app/src/services/cpk.ts
  app/src/services/index.ts
  app/src/services/ovm.ts
Labels: verification

#1394 changed color of challengeable market eth
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1395 Fix/#1339 consolidate spinners
  app/src/components/common/icons/IconSpinner.tsx
  app/src/components/common/icons/index.ts
  app/src/components/common/spinner/img/spinnerMain.svg
  app/src/components/common/spinner/img/spinnerMainBig.svg
  app/src/components/common/spinner/index.tsx
  app/src/components/market/common/currency_selector/index.tsx
  app/src/components/market/common/customizable_tokens_select/modal_collateral.tsx
  app/src/components/market/sections/market_create/steps/items/import_market_content.tsx
  app/src/components/market/sections/market_verify/market_verify.tsx
Labels: verification

#1397 Fix/#1387 time remaining message
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification

#1399 button styling seems to be overwritten
  app/src/components/market/sections/market_verify/option/kleros_curation.tsx
Labels: verification
