Repository protofire/omen-exchange, pull requests merged in 2021-08, with the labels that each got.

#2138 Pool liquidity component consolidation
  app/src/components/index.ts
  app/src/components/market/sections/market_pooling/market_pool_liquidity.tsx
  app/src/components/market/sections/market_pooling/market_pool_liquidity_container.tsx
  app/src/components/market/sections/market_pooling/scalar_market_pool_liquidity.tsx
  app/src/components/market/sections/market_profile/market_status/closed.tsx
  app/src/components/market/sections/market_profile/market_status/open.tsx
  app/src/pages/market_sections/market_pool_liquidity_container.tsx
Labels: REFACTOR

#2110 refactor: In progress, moved shared logic into market_buy_container
  app/src/components/index.ts
  app/src/components/market/common/outcome_table/index.tsx
  app/src/components/market/sections/market_buy/market_buy.tsx
  app/src/components/market/sections/market_buy/market_buy_container.tsx
  app/src/components/market/sections/market_buy/scalar_market_buy.tsx
  app/src/components/market/sections/market_profile/market_status/closed.tsx
  app/src/components/market/sections/market_profile/market_status/open.tsx
  app/src/pages/market_sections/market_buy_container.tsx
Labels: REFACTOR

#2090 Format Big Numbers doesn't need wrapper
  app/src/components/common/layout/header/index.tsx
  app/src/components/market/common/currency_selector/index.tsx
  app/src/components/market/common/history_section/history_select.tsx
  app/src/components/market/common/history_table/index.tsx
  app/src/components/market/common/list_item/index.tsx
  app/src/components/market/common/market_data/index.tsx
  app/src/components/market/common/market_resolution_message/index.tsx
  app/src/components/market/common/market_scale/index.tsx
  app/src/components/market/common/market_top_details_closed/index.tsx
  app/src/components/market/common/market_top_details_open/index.tsx
  app/src/components/market/common/outcome_table/index.tsx
  app/src/components/market/common/position_selection_box/index.tsx
  app/src/components/market/common/position_table/index.tsx
  app/src/components/market/common/transaction_details_row/index.tsx
  app/src/components/market/sections/market_bond/market_bond.tsx
  app/src/components/market/sections/market_buy/market_buy.tsx
  app/src/components/market/sections/market_buy/scalar_market_buy.tsx
  app/src/components/market/sections/market_create/steps/items/create_scalar_market.tsx
  app/src/components/market/sections/market_create/steps/items/funding_and_fee_step.tsx
  app/src/components/market/sections/market_pooling/market_pool_liquidity.tsx
  app/src/components/market/sections/market_pooling/scalar_market_pool_liquidity.tsx
  app/src/components/market/sections/market_pooling/user_pool_data.tsx
  app/src/components/market/sections/market_profile/market_status/closed.tsx
  app/src/components/market/sections/market_sell/market_sell.tsx
  app/src/components/market/sections/market_sell/scalar_market_sell.tsx
  app/src/components/modal/modal_deposit_withdraw/index.tsx
  app/src/components/modal/modal_your_connection/index.tsx
  app/src/hooks/useBalance.tsx
  app/src/hooks/useTheme.tsx
  app/src/pages/market_sections/market_buy_container.tsx
  app/src/pages/market_sections/market_pool_liquidity_container.tsx
  app/src/pages/market_sections/market_sell_container.tsx
  app/src/util/tools/formatting.ts
  app/src/util/tools/fpmm/trading/index.ts
  app/src/util/tools/tools.spec.ts
  app/src/util/types.ts
Labels: REFACTOR

#2180 Voting power transition fix
  app/src/components/modal/modal_lock_yo_tokens/index.tsx
Labels: bug

#2183 Fix: Move SetAllowance component below (updated after guild merge) - V2
  app/src/components/market/market_bond/market_bond.tsx
Labels: enhancement, UI

#2182 Fix: Font-size and margin on Settings and broken RPC
  app/src/App.tsx
  app/src/components/button/button_round/index.tsx
  app/src/components/settings/settings_view/index.tsx
Labels: UI, Guild

#2206 Ref: Refactor of Modal Your Connection with new theme
  app/src/components/modal/common_styled/index.tsx
  app/src/components/modal/modal_your_connection/index.tsx
  app/src/theme/index.tsx
Labels: UI, REFACTOR

#2213 Ref: Refactored Transaction modal with new theme colours and texts
  app/src/components/modal/modal_transaction/index.tsx
Labels: UI, REFACTOR

#2217 Fix: Fixed dynamic text for set allowance button
  app/src/components/market/common_sections/allowance/set_allowance/index.tsx
  app/src/components/market/common_sections/allowance/toggle_token_lock/index.tsx
Labels: UI

#2169 Feature: Add 2.5% potential fee info when user wants to bond on an ou…
  app/src/components/market/market_bond/market_bond.tsx
Labels: UI, Guild

#2185 Ref: Update colours and text with new theme in Airdrop Modal
  app/src/components/modal/modal_airdrop/airdrop_card.tsx
  app/src/components/modal/modal_airdrop/check_address.tsx
  app/src/components/modal/modal_lock_yo_tokens/index.tsx
  app/src/theme/index.tsx
  app/src/theme/types.ts
Labels: UI, Guild, REFACTOR

#2212 Ref: Refactored Connect Wallet Modal with new theme colours and text
  app/src/components/modal/modal_connect_wallet/index.tsx
Labels: UI, REFACTOR
