Repository protofire/omen-exchange, pull requests merged in 2021-01, with the labels that each got.

#1262 wip: support native ether
  app/src/common/constants.ts
  app/src/components/market/common/currency_selector/index.tsx
  app/src/components/market/common/outcome_table/index.tsx
  app/src/components/market/sections/market_buy/market_buy.tsx
  app/src/components/market/sections/market_create/market_wizard_creator_container.tsx
  app/src/components/market/sections/market_create/steps/items/funding_and_fee_step.tsx
  app/src/components/market/sections/market_pooling/market_pool_liquidity.tsx
  app/src/global.d.ts
  app/src/hooks/index.ts
  app/src/hooks/useCollateralBalance.tsx
  app/src/hooks/useCpkAllowance.tsx
  app/src/hooks/useCpkProxy.tsx
  app/src/hooks/useTokens.tsx
  app/src/services/cpk.ts
  app/src/store/reducer.ts
  app/src/util/cpk.ts
  app/src/util/networks.ts
  app/yarn.lock
Labels: Gnosis Safe

#1566 Update xDai CPK Proxy Factory
  app/src/services/cpk.ts
  app/src/util/networks.ts
Labels: Gnosis Safe, xDai

#1582 Fix/#1532
  app/src/components/market/sections/market_create/steps/items/import_market_content.tsx
  app/src/hooks/useBlockchainMarketMakerData.tsx
  app/src/hooks/useGraphMarketsFromQuestion.tsx
  app/src/hooks/useMarketMakerData.ts
Labels: bug

#1586 fix dropdown control issues
  app/src/components/common/form/dropdown/index.tsx
Labels: bug
